### ISSUE TITLE
Example wrong 

### ISSUE THREAD

**Issue by awb99** [soliton4/promiseland#2]
The second example misses the return value doIt 

```
if (*userInput()){
var result = *readFile();
processFile(result);
}

```

**Comment by awb99** [comment]
if (*userInput()){
  var result = *readFile();
  pSip par conseguir nuestro beberocessFile(result);
};Sip par conseguir nuestro bebe

**Comment by awb99** [comment]
if (*userInput()){
  var result = *readFile();
  processFile(result);
}

**Comment by soliton4** [comment]
i do not understand

**Comment by awb99** [comment]
userInput().then(function(doIt){
  if (doIt){
    var result;
    readFile().then(function(parRes){
      result = parRes;
      processFile(result);
    });
  };
});

**Comment by awb99** [comment]
The Javascript example has some data in doIt? 
Or is it just  Boolean?

**Comment by soliton4** [comment]
doit is the parameter of the function passed to the then method of the promise.
its supposed to be interpreted as boolean
